# Generated by Django 3.2.3 on 2021-05-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField()),
                ('project_startdate', models.DateField()),
                ('project_enddate', models.DateField()),
                ('project_status', models.CharField(choices=[('INC', 'Incomplete'), ('COMP', 'Complete')], max_length=4)),
                ('agencyprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agencyprofile')),
                ('clientprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile')),
            ],
        ),
    ]
