# Generated by Django 3.2.3 on 2021-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name_plural': 'Agency Contacts',
            },
        ),
        migrations.CreateModel(
            name='AgencyExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_categories', models.CharField(choices=[('IT', 'Information Technology'), ('BP', 'Business Planning')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Agency Expertise',
            },
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experienceyears', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Agency Profiles',
            },
        ),
    ]
