# Generated by Django 3.1.5 on 2021-06-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_auto_20210531_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyexpertise',
            name='agencyprofile',
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='phonenumber',
            field=models.CharField(default=2, max_length=13),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AgencyContacts',
        ),
        migrations.DeleteModel(
            name='AgencyExpertise',
        ),
    ]
