# Generated by Django 3.2.3 on 2021-05-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clientprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile'),
        ),
    ]
