# Generated by Django 3.1.5 on 2021-06-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210531_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phonenumber',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientContacts',
        ),
    ]
